def make_html_table(df) -> str:
    """
    Create a color-coded HTML table from results DataFrame.
    
    Args:
        df: Results DataFrame with GP calculations
        
    Returns:
        str: HTML table string
    """
    def get_gp_color(gp_pct):
        """Get color based on GP percentage."""
        if gp_pct >= 70:
            return "#3CB371"  # Green
        elif gp_pct >= 65:
            return "#FFB84D"  # Orange
        else:
            return "#FF6B6B"  # Red
    
    # Start building HTML
    html = '<div style="font-family: Arial, sans-serif; margin: 20px;">'
    html += '''
    <div style="text-align: center; margin-bottom: 30px; padding: 20px; background: linear-gradient(135deg, #ff6b35, #f7931e); border-radius: 15px; color: white;">
        <div style="font-size: 48px; margin-bottom: 10px;">👹</div>
        <h1 style="margin: 0; font-size: 2.5rem; font-weight: bold; text-shadow: 2px 2px 4px rgba(0,0,0,0.3);">HUNGRY TUM</h1>
        <p style="margin: 5px 0 0 0; font-size: 1.2rem; opacity: 0.9;">Food Cost Analysis</p>
    </div>
    '''
    html += '<table style="width:100%; border-collapse: collapse; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">'
    
    # Header row
    html += '<tr style="background: linear-gradient(135deg, #667eea, #764ba2); color: white; font-weight: bold;">'
    for col in df.columns:
        html += f'<td style="border: 1px solid #ddd; padding: 12px; text-align: center;">{col}</td>'
    html += '</tr>'
    
    # Data rows
    for i, (_, row) in enumerate(df.iterrows()):
        bg_color = "#fafafa" if i % 2 == 0 else "#ffffff"
        html += f'<tr style="background: {bg_color}; transition: background-color 0.2s;">'
        
        for col in df.columns:
            val = row[col]
            style = "border: 1px solid #ddd; padding: 10px;"
            
            if col == "GP %":
                color = get_gp_color(val)
                style += f"text-align: right; color: {color}; font-weight: bold;"
                val = f"{val}%"
            elif "£" in col:
                style += "text-align: right; font-family: monospace;"
                val = f"£{val}"
            else:
                style += "text-align: left;"
            
            html += f'<td style="{style}">{val}</td>'
        
        html += "</tr>"
    
    html += "</table>"
    
    # Summary stats
    total_items = len(df)
    avg_gp = df["GP %"].mean()
    high_gp_items = len(df[df["GP %"] >= 70])
    low_gp_items = len(df[df["GP %"] < 65])
    
    html += f'''
    <div style="margin-top: 20px; padding: 15px; background: #f8f9fa; border-radius: 8px;">
        <h3 style="color: #333; margin-bottom: 10px;">📊 Summary</h3>
        <p><strong>Total Items:</strong> {total_items}</p>
        <p><strong>Average GP:</strong> {avg_gp:.1f}%</p>
        <p style="color: #3CB371;"><strong>High Margin Items (≥70%):</strong> {high_gp_items}</p>
        <p style="color: #FF6B6B;"><strong>Low Margin Items (<65%):</strong> {low_gp_items}</p>
    </div>
    
    <div style="margin-top: 15px; padding: 10px; background: #e3f2fd; border-left: 4px solid #2196f3; border-radius: 4px;">
        <p style="margin: 0; font-style: italic; color: #666;">
            Generated by Hungry Tum | Food Cost Generator
        </p>
    </div>
    </div>
    '''
    
    return html
