def make_html_table(df) -> str:
    """
    Create a color-coded HTML table from results DataFrame.
    
    Args:
        df: Results DataFrame with GP calculations
        
    Returns:
        str: HTML table string
    """
    def get_gp_color(gp_pct):
        """Get color based on GP percentage."""
        if gp_pct >= 70:
            return "#3CB371"  # Green
        elif gp_pct >= 65:
            return "#FFB84D"  # Orange
        else:
            return "#FF6B6B"  # Red
    
    # Start building HTML
    html = '<div style="font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 20px;">'
    html += '''
    <div style="text-align: center; margin-bottom: 30px; padding: 30px; background: linear-gradient(135deg, #2c3e50, #34495e); border-radius: 12px; color: white; box-shadow: 0 8px 32px rgba(0,0,0,0.1);">
        <div style="margin-bottom: 20px;">
            <img src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAiIGhlaWdodD0iODAiIHZpZXdCb3g9IjAgMCA4MCA4MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iNDAiIGN5PSI0MCIgcj0iMzgiIGZpbGw9IiNmZjZiMzUiLz4KPGNpcmNsZSBjeD0iMzAiIGN5PSIzMCIgcj0iOCIgZmlsbD0id2hpdGUiLz4KPGNpcmNsZSBjeD0iNTAiIGN5PSIzMCIgcj0iOCIgZmlsbD0id2hpdGUiLz4KPGNpcmNsZSBjeD0iMzAiIGN5PSIzMCIgcj0iNCIgZmlsbD0iYmxhY2siLz4KPGNpcmNsZSBjeD0iNTAiIGN5PSIzMCIgcj0iNCIgZmlsbD0iYmxhY2siLz4KPHBhdGggZD0iTTI1IDU1IEMzMCA1MCA0MCA1MCA0MCA1MCBDNDAgNTAgNTAgNTAgNTUgNTUiIHN0cm9rZT0iYmxhY2siIHN0cm9rZS13aWR0aD0iMyIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIi8+CjxwYXRoIGQ9Ik0yMCAyMCBDMjAgMTUgMjUgMTAgMzAgMTAgQzM1IDEwIDQwIDE1IDQwIDIwIiBzdHJva2U9IiNmZjZiMzUiIHN0cm9rZS13aWR0aD0iNCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIi8+CjxwYXRoIGQ9Ik00MCAyMCBDNDAgMTUgNDUgMTAgNTAgMTAgQzU1IDEwIDYwIDE1IDYwIDIwIiBzdHJva2U9IiNmZjZiMzUiIHN0cm9rZS13aWR0aD0iNCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIi8+Cjwvc3ZnPgo=" alt="Hungry Tum Logo" style="width: 80px; height: 80px; margin-bottom: 15px;">
        </div>
        <h1 style="margin: 0; font-size: 2.8rem; font-weight: 700; letter-spacing: 2px; text-shadow: 2px 2px 4px rgba(0,0,0,0.3);">HUNGRY TUM</h1>
        <p style="margin: 8px 0 0 0; font-size: 1.1rem; opacity: 0.9; font-weight: 300;">Food Cost Analysis</p>
    </div>
    '''
    html += '<table style="width:100%; border-collapse: collapse; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">'
    
    # Header row
    html += '<tr style="background: linear-gradient(135deg, #34495e, #2c3e50); color: white; font-weight: 600; font-size: 0.9rem;">'
    for col in df.columns:
        html += f'<td style="border: 1px solid #ddd; padding: 12px; text-align: center;">{col}</td>'
    html += '</tr>'
    
    # Data rows
    for i, (_, row) in enumerate(df.iterrows()):
        bg_color = "#fafafa" if i % 2 == 0 else "#ffffff"
        html += f'<tr style="background: {bg_color}; transition: background-color 0.2s;">'
        
        for col in df.columns:
            val = row[col]
            style = "border: 1px solid #ddd; padding: 10px;"
            
            if col == "GP %":
                color = get_gp_color(val)
                style += f"text-align: right; color: {color}; font-weight: bold;"
                val = f"{val}%"
            elif "£" in col:
                style += "text-align: right; font-family: monospace;"
                val = f"£{val}"
            else:
                style += "text-align: left;"
            
            html += f'<td style="{style}">{val}</td>'
        
        html += "</tr>"
    
    html += "</table>"
    
    # Summary stats
    total_items = len(df)
    avg_gp = df["GP %"].mean()
    high_gp_items = len(df[df["GP %"] >= 70])
    low_gp_items = len(df[df["GP %"] < 65])
    
    html += f'''
    <div style="margin-top: 20px; padding: 15px; background: #f8f9fa; border-radius: 8px;">
        <h3 style="color: #333; margin-bottom: 10px;">📊 Summary</h3>
        <p><strong>Total Items:</strong> {total_items}</p>
        <p><strong>Average GP:</strong> {avg_gp:.1f}%</p>
        <p style="color: #3CB371;"><strong>High Margin Items (≥70%):</strong> {high_gp_items}</p>
        <p style="color: #FF6B6B;"><strong>Low Margin Items (<65%):</strong> {low_gp_items}</p>
    </div>
    
    <div style="margin-top: 15px; padding: 10px; background: #e3f2fd; border-left: 4px solid #2196f3; border-radius: 4px;">
        <p style="margin: 0; font-style: italic; color: #666;">
            Generated by Hungry Tum | Food Cost Generator
        </p>
    </div>
    </div>
    '''
    
    return html
